[0.629s] Invoking command in '/home/absolutezeno/Auto-BT-Generation/build/custom_message': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/absolutezeno/Auto-BT-Generation/install/py_trees_ros_viewer:/home/absolutezeno/Auto-BT-Generation/install/py_trees_ros_tutorials:/home/absolutezeno/Auto-BT-Generation/install/py_trees_ros:/home/absolutezeno/FRA501/install/rqt_joint_trajectory_controller:/home/absolutezeno/FRA501/install/rqt_controller_manager:/home/absolutezeno/FRA501/install/ros2controlcli:/home/absolutezeno/FRA501/install/ros2_controllers_test_nodes:/opt/ros/humble PS1=(isaaclab) \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ VIRTUAL_ENV_PROMPT=(isaaclab) /usr/bin/cmake /home/absolutezeno/Auto-BT-Generation/src/custom_message -DCMAKE_INSTALL_PREFIX=/home/absolutezeno/Auto-BT-Generation/install/custom_message
[0.641s] -- Found ament_cmake: 1.3.5 (/opt/ros/humble/share/ament_cmake/cmake)
[0.767s] -- Found std_msgs: 4.2.4 (/opt/ros/humble/share/std_msgs/cmake)
[0.782s] -- Found rosidl_generator_c: 3.1.5 (/opt/ros/humble/share/rosidl_generator_c/cmake)
[0.783s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.787s] -- Found rosidl_generator_cpp: 3.1.5 (/opt/ros/humble/share/rosidl_generator_cpp/cmake)
[0.793s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.803s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.835s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.938s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.938s]   execute_process(/home/absolutezeno/isaaclab/bin/python3.10 -m
[0.938s]   rosidl_adapter --package-name custom_message --arguments-file
[0.938s]   /home/absolutezeno/Auto-BT-Generation/build/custom_message/rosidl_adapter__arguments__custom_message.json
[0.938s]   --output-dir
[0.939s]   /home/absolutezeno/Auto-BT-Generation/build/custom_message/rosidl_adapter/custom_message
[0.939s]   --output-file
[0.939s]   /home/absolutezeno/Auto-BT-Generation/build/custom_message/rosidl_adapter/custom_message.idls)
[0.939s]   returned error code 1:
[0.939s] 
[0.940s]   AttributeError processing template 'msg.idl.em'
[0.940s] 
[0.940s]   Traceback (most recent call last):
[0.940s] 
[0.941s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 51, in evaluate_template
[0.941s]       em.BUFFERED_OPT: True,
[0.941s] 
[0.941s]   AttributeError: module 'em' has no attribute 'BUFFERED_OPT'
[0.941s] 
[0.941s]   
[0.942s] 
[0.942s]   During handling of the above exception, another exception occurred:
[0.942s] 
[0.943s]   
[0.943s] 
[0.943s]   Traceback (most recent call last):
[0.943s] 
[0.944s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.944s]       return _run_code(code, main_globals, None,
[0.944s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.944s]       exec(code, run_globals)
[0.945s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.945s]       sys.exit(main())
[0.945s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.945s]       abs_idl_file = convert_to_idl(
[0.946s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.946s]       return convert_msg_to_idl(
[0.946s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 39, in convert_msg_to_idl
[0.946s]       expand_template('msg.idl.em', data, output_file, encoding='iso-8859-1')
[0.947s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 23, in expand_template
[0.947s]       content = evaluate_template(template_name, data)
[0.947s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/resource/__init__.py", line 69, in evaluate_template
[0.947s]       _interpreter.shutdown()
[0.947s] 
[0.948s]   AttributeError: 'NoneType' object has no attribute 'shutdown'
[0.948s] 
[0.949s] Call Stack (most recent call first):
[0.950s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.950s]   CMakeLists.txt:23 (rosidl_generate_interfaces)
[0.950s] 
[0.950s] [0m
[0.950s] -- Configuring incomplete, errors occurred!
[0.950s] See also "/home/absolutezeno/Auto-BT-Generation/build/custom_message/CMakeFiles/CMakeOutput.log".
[0.971s] Invoked command in '/home/absolutezeno/Auto-BT-Generation/build/custom_message' returned '1': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/absolutezeno/Auto-BT-Generation/install/py_trees_ros_viewer:/home/absolutezeno/Auto-BT-Generation/install/py_trees_ros_tutorials:/home/absolutezeno/Auto-BT-Generation/install/py_trees_ros:/home/absolutezeno/FRA501/install/rqt_joint_trajectory_controller:/home/absolutezeno/FRA501/install/rqt_controller_manager:/home/absolutezeno/FRA501/install/ros2controlcli:/home/absolutezeno/FRA501/install/ros2_controllers_test_nodes:/opt/ros/humble PS1=(isaaclab) \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ VIRTUAL_ENV_PROMPT=(isaaclab) /usr/bin/cmake /home/absolutezeno/Auto-BT-Generation/src/custom_message -DCMAKE_INSTALL_PREFIX=/home/absolutezeno/Auto-BT-Generation/install/custom_message
